apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-label-value
  name: doggo-fe-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: doggo-fe-port
      port: 80
      protocol: TCP
  selector:
    deployment-label-key: doggo-fe
